apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xafm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xafm
    app.kubernetes.io/part-of: tkrw-pr712-0075-0039-app
  name: devfile-sample-xafm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-xafm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-xafm
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0039-tenant/tkrw-pr712-0075-0039-app/devfile-sample-xafm@sha256:b3cffed7c0c7b67f57bb19acf2d715fcf8506a10b0c2bcf659f09f795432844d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
